### PR TITLE
feat(liveliness-probe): adding probe capability to proxy image

### PR DESCRIPTION
**Pull request by brandonrjacobs**

### CODE REVIEW

**Comment by salanki** [comment]
I didn't even see this. Is there a matching PR to k8s-services?

**Comment by brandonrjacobs** [comment]
@salanki I had to fix a few CI issues and the liveliness script but this should be good to go.

**Comment by salanki** [comment]
This PR does too many things.

1 PR for rebasing on master (don’t merge our changes, rebase on top of origin)
1 PR for CI
1 PR for liveness

**Comment by brandonrjacobs** [comment]
Ok making new PR's.

**Pull request closed without merging**
